export type ReviewRegisterState = {
  COMPONENT_HANDLER: number;
  POSTCODE_OPEN: boolean;
  ADDRESS_OPEN: boolean;
  userId: string;
  content: string;
  address: string;
  addressDetail: string;
  sigungu: string;
  dong: string;
  total: string[];
  totalNum: number;
  totalUrl: string[];
  clean: string;
  sound: string;
  accessible: string;
  landlord: string;
  facility: string;
  periodFrom: string;
  periodTo: string;
  Reviewfile: string[];
  ReviewfileUrl: string[];
};
