export type RoomRegisterState = {
  COMPONENT_HANDLER: number;
  POSTCODE_OPEN: boolean;
  ADDRESS_OPEN: boolean;
  DETAIL_COMPONENT_OPEN: boolean;
  longitude: number;
  latitude: number;
  userId: string;
  sigungu: string;
  dong: string;
  address: string;
  addressDetail: string;
  roomType: string;
  dealType: string;
  priceUnit: string;
  deposit: number | string;
  price: number | string;
  manage: 0 | 1;
  managementCost: number | string;
  utility: Array<number>;
  totalFloor: number | string;
  floor: number | string;
  structure: string;
  roomSize: number | string;
  startedAt: string;
  finishedAt: string;
  tenancyAgreement : 0 | 1;
  optionAll: 0 | 1;
  option: Array<number>;
  advantage: Array<number>;
  elevator: 0 | 1;
  car: 0 | 1 | 2;
  pet: 0 | 1 | 2;
  women: 0 | 1 | 2;
  loan: 0 | 1 | 2;
  title: string;
  content: string;
  mainImage: string[];
  mainImageUrl: string[];
  room1Image: string[];
  room1ImageUrl: string[];
  room2Image: string[];
  room2ImageUrl: string[];
};
